#!/usr/bin/sh
sudo apt-get update && sudo apt-get upgrade -y

# Install Nix
# sh <(curl -L https://nixos.org/nix/install) --daemon --yes

# Install Zsh
sudo apt-get install -y zsh
chsh -s $(which zsh)

# install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# oh-my-zsh plugin installation
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Install starship
export STARSHIP_CONFIG=$HOME/.starship/config.toml
sudo sh -c "$(curl -sS https://starship.rs/install.sh)" "" --yes
# mkdir -p ~/.config && touch ~/.config/starship.toml

# Install Python packages
python3 -m pip install --user argcomplete

# Install Daytona
# sh -C "$(curl -sf -L https://download.daytona.io/daytona/install.sh | sudo bash) && daytona server -y && daytona"

# Install tmux
sudo apt-get install -y tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Install stow
sudo apt-get install -y stow
# stow -D --target=$HOME .
chmod +x stow.sh && ./stow.sh

# Install minikube
curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
curl -sS https://webi.sh/k9s | sh

# Install Helm
sudo apt-get install curl gpg apt-transport-https --yes
curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
echo "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
sudo apt-get update
sudo apt-get install helm
